const CONFIG = {
	langList: ["en", "zh-CN"],
	color: [
		"#fff",
		"#eee",
		"#ddd",
		"#ccc",
		"#bbb",
		"#000",
		"#CCFFFF",
		"#CCFFCC",
		"#f5f5dc",
		"#8a2be2",
		"#008b8b",
		"#CCFF00",
		"#FF9900",
		"#66FF00",
		"#FF3399",
		"#00ffff",
		"#ff0000",
		"#FF3300",
		"#FFFF00",
		"#99CC00",
		"#009900",
		"#66CC00",
		"#660000",
		"#3366FF",
	],
	toolbars: {
		bold: true,
		italic: true,
		header: true,
		underline: true,
		strikethrough: true,
		mark: true,
		superscript: true,
		subscript: false,
		quote: true,
		ol: true,
		ul: true,
		link: true,
		color: true,
		imagelink: true,
		code: true,
		table: true,
		undo: true,
		redo: true,
		trash: true,
		save: true,
		alignleft: true,
		aligncenter: true,
		alignright: true,
		navigation: true,
		subfield: true,
		fullscreen: true,
		readmodel: true,
		htmlcode: true,
		help: true,
		preview: true,
	},
};
export default CONFIG;
